services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nm-portfolio-api-prod
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    restart: unless-stopped
